# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-13
  strategy:
    matrix:
      osx_64_numpy2.0python3.10.____cpythonvariantall:
        CONFIG: osx_64_numpy2.0python3.10.____cpythonvariantall
        UPLOAD_PACKAGES: 'True'
      osx_64_numpy2.0python3.10.____cpythonvariantnovtk:
        CONFIG: osx_64_numpy2.0python3.10.____cpythonvariantnovtk
        UPLOAD_PACKAGES: 'True'
      osx_64_numpy2.0python3.11.____cpythonvariantall:
        CONFIG: osx_64_numpy2.0python3.11.____cpythonvariantall
        UPLOAD_PACKAGES: 'True'
      osx_64_numpy2.0python3.11.____cpythonvariantnovtk:
        CONFIG: osx_64_numpy2.0python3.11.____cpythonvariantnovtk
        UPLOAD_PACKAGES: 'True'
      osx_64_numpy2.0python3.12.____cpythonvariantall:
        CONFIG: osx_64_numpy2.0python3.12.____cpythonvariantall
        UPLOAD_PACKAGES: 'True'
      osx_64_numpy2.0python3.12.____cpythonvariantnovtk:
        CONFIG: osx_64_numpy2.0python3.12.____cpythonvariantnovtk
        UPLOAD_PACKAGES: 'True'
      osx_64_numpy2.0python3.13.____cp313variantall:
        CONFIG: osx_64_numpy2.0python3.13.____cp313variantall
        UPLOAD_PACKAGES: 'True'
      osx_64_numpy2.0python3.13.____cp313variantnovtk:
        CONFIG: osx_64_numpy2.0python3.13.____cp313variantnovtk
        UPLOAD_PACKAGES: 'True'
      osx_64_numpy2python3.10.____cpythonvariantall:
        CONFIG: osx_64_numpy2python3.10.____cpythonvariantall
        UPLOAD_PACKAGES: 'True'
      osx_64_numpy2python3.10.____cpythonvariantnovtk:
        CONFIG: osx_64_numpy2python3.10.____cpythonvariantnovtk
        UPLOAD_PACKAGES: 'True'
      osx_64_numpy2python3.11.____cpythonvariantall:
        CONFIG: osx_64_numpy2python3.11.____cpythonvariantall
        UPLOAD_PACKAGES: 'True'
      osx_64_numpy2python3.11.____cpythonvariantnovtk:
        CONFIG: osx_64_numpy2python3.11.____cpythonvariantnovtk
        UPLOAD_PACKAGES: 'True'
      osx_64_numpy2python3.12.____cpythonvariantall:
        CONFIG: osx_64_numpy2python3.12.____cpythonvariantall
        UPLOAD_PACKAGES: 'True'
      osx_64_numpy2python3.12.____cpythonvariantnovtk:
        CONFIG: osx_64_numpy2python3.12.____cpythonvariantnovtk
        UPLOAD_PACKAGES: 'True'
      osx_64_numpy2python3.13.____cp313variantall:
        CONFIG: osx_64_numpy2python3.13.____cp313variantall
        UPLOAD_PACKAGES: 'True'
      osx_64_numpy2python3.13.____cp313variantnovtk:
        CONFIG: osx_64_numpy2python3.13.____cp313variantnovtk
        UPLOAD_PACKAGES: 'True'
      osx_arm64_numpy2.0python3.10.____cpythonvariantall:
        CONFIG: osx_arm64_numpy2.0python3.10.____cpythonvariantall
        UPLOAD_PACKAGES: 'True'
      osx_arm64_numpy2.0python3.10.____cpythonvariantnovtk:
        CONFIG: osx_arm64_numpy2.0python3.10.____cpythonvariantnovtk
        UPLOAD_PACKAGES: 'True'
      osx_arm64_numpy2.0python3.11.____cpythonvariantall:
        CONFIG: osx_arm64_numpy2.0python3.11.____cpythonvariantall
        UPLOAD_PACKAGES: 'True'
      osx_arm64_numpy2.0python3.11.____cpythonvariantnovtk:
        CONFIG: osx_arm64_numpy2.0python3.11.____cpythonvariantnovtk
        UPLOAD_PACKAGES: 'True'
      osx_arm64_numpy2.0python3.12.____cpythonvariantall:
        CONFIG: osx_arm64_numpy2.0python3.12.____cpythonvariantall
        UPLOAD_PACKAGES: 'True'
      osx_arm64_numpy2.0python3.12.____cpythonvariantnovtk:
        CONFIG: osx_arm64_numpy2.0python3.12.____cpythonvariantnovtk
        UPLOAD_PACKAGES: 'True'
      osx_arm64_numpy2.0python3.13.____cp313variantall:
        CONFIG: osx_arm64_numpy2.0python3.13.____cp313variantall
        UPLOAD_PACKAGES: 'True'
      osx_arm64_numpy2.0python3.13.____cp313variantnovtk:
        CONFIG: osx_arm64_numpy2.0python3.13.____cp313variantnovtk
        UPLOAD_PACKAGES: 'True'
      osx_arm64_numpy2python3.10.____cpythonvariantall:
        CONFIG: osx_arm64_numpy2python3.10.____cpythonvariantall
        UPLOAD_PACKAGES: 'True'
      osx_arm64_numpy2python3.10.____cpythonvariantnovtk:
        CONFIG: osx_arm64_numpy2python3.10.____cpythonvariantnovtk
        UPLOAD_PACKAGES: 'True'
      osx_arm64_numpy2python3.11.____cpythonvariantall:
        CONFIG: osx_arm64_numpy2python3.11.____cpythonvariantall
        UPLOAD_PACKAGES: 'True'
      osx_arm64_numpy2python3.11.____cpythonvariantnovtk:
        CONFIG: osx_arm64_numpy2python3.11.____cpythonvariantnovtk
        UPLOAD_PACKAGES: 'True'
      osx_arm64_numpy2python3.12.____cpythonvariantall:
        CONFIG: osx_arm64_numpy2python3.12.____cpythonvariantall
        UPLOAD_PACKAGES: 'True'
      osx_arm64_numpy2python3.12.____cpythonvariantnovtk:
        CONFIG: osx_arm64_numpy2python3.12.____cpythonvariantnovtk
        UPLOAD_PACKAGES: 'True'
      osx_arm64_numpy2python3.13.____cp313variantall:
        CONFIG: osx_arm64_numpy2python3.13.____cp313variantall
        UPLOAD_PACKAGES: 'True'
      osx_arm64_numpy2python3.13.____cp313variantnovtk:
        CONFIG: osx_arm64_numpy2python3.13.____cp313variantnovtk
        UPLOAD_PACKAGES: 'True'
    maxParallel: 20
  timeoutInMinutes: 360
  variables: {}

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export flow_run_id=azure_$(Build.BuildNumber).$(System.JobAttempt)
      export remote_url=$(Build.Repository.Uri)
      export sha=$(Build.SourceVersion)
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
        export IS_PR_BUILD="True"
      else
        export IS_PR_BUILD="False"
      fi
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
